# Generated by Django 3.1.7 on 2021-08-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart__and__favorites', '0002_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
