# Generated by Django 3.1.7 on 2021-08-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name_plural': 'Reviews'},
        ),
        migrations.AddField(
            model_name='product',
            name='sex',
            field=models.CharField(blank=True, choices=[('women', 'Women'), ('man', 'Man'), ('Children', 'Children')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='views',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
